'use strict';

const errorNotImplemented = require('./index').errorNotImplemented;

const _POST_PRODUCT_DATA_ = errorNotImplemented('_POST_PRODUCT_DATA_');
const _POST_INVENTORY_AVAILABILITY_DATA_ = errorNotImplemented('_POST_INVENTORY_AVAILABILITY_DATA_');
const _POST_PRODUCT_OVERRIDES_DATA_ = errorNotImplemented('_POST_PRODUCT_OVERRIDES_DATA_');
const _POST_PRODUCT_PRICING_DATA_ = errorNotImplemented('_POST_PRODUCT_PRICING_DATA_');
const _POST_PRODUCT_IMAGE_DATA_ = errorNotImplemented('_POST_PRODUCT_IMAGE_DATA_');
const _POST_PRODUCT_RELATIONSHIP_DATA_ = errorNotImplemented('_POST_PRODUCT_RELATIONSHIP_DATA_');
const _POST_FLAT_FILE_INVLOADER_DATA_ = errorNotImplemented('_POST_FLAT_FILE_INVLOADER_DATA_');
const _POST_FLAT_FILE_LISTINGS_DATA_ = errorNotImplemented('_POST_FLAT_FILE_LISTINGS_DATA_');
const _POST_FLAT_FILE_BOOKLOADER_DATA_ = errorNotImplemented('_POST_FLAT_FILE_BOOKLOADER_DATA_');
const _POST_FLAT_FILE_CONVERGENCE_LISTINGS_DATA_ = errorNotImplemented('_POST_FLAT_FILE_CONVERGENCE_LISTINGS_DATA_');
// const _POST_FLAT_FILE_LISTINGS_DATA_ = errorNotImplemented('____________');
const _POST_FLAT_FILE_PRICEANDQUANTITYONLY_UPDATE_DATA_ = errorNotImplemented('_POST_FLAT_FILE_PRICEANDQUANTITYONLY_UPDATE_DATA_');
const _POST_UIEE_BOOKLOADER_DATA_ = errorNotImplemented('_POST_UIEE_BOOKLOADER_DATA_');
const _POST_STD_ACES_DATA_ = errorNotImplemented('_POST_STD_ACES_DATA_');

module.exports = {
    _POST_PRODUCT_DATA_,
    _POST_INVENTORY_AVAILABILITY_DATA_,
    _POST_PRODUCT_OVERRIDES_DATA_,
    _POST_PRODUCT_PRICING_DATA_,
    _POST_PRODUCT_IMAGE_DATA_,
    _POST_PRODUCT_RELATIONSHIP_DATA_,
    _POST_FLAT_FILE_INVLOADER_DATA_,
    _POST_FLAT_FILE_LISTINGS_DATA_,
    _POST_FLAT_FILE_BOOKLOADER_DATA_,
    _POST_FLAT_FILE_CONVERGENCE_LISTINGS_DATA_,
    // _POST_FLAT_FILE_LISTINGS_DATA_,
    _POST_FLAT_FILE_PRICEANDQUANTITYONLY_UPDATE_DATA_,
    _POST_UIEE_BOOKLOADER_DATA_,
    _POST_STD_ACES_DATA_
};
